#!/bin/sh
# Tests for the watcher auto-update logic (watcher_lib.sh: read_options,
# provider_src, fetch_latest) generated by scripts/install_watcher_addon.sh.
#
# Run from the repo root:   sh tests/test_watcher_autoupdate.sh
#
# Generating the add-on downloads the provider from GitHub; if that fails
# (offline) the whole suite auto-skips. Set SKIP_NETWORK_TESTS=1 to skip.

set -u
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT="$REPO_ROOT/scripts/install_watcher_addon.sh"
PASS=0; FAIL=0; SKIP=0
red(){ printf '\033[31m%s\033[0m' "$*"; }; green(){ printf '\033[32m%s\033[0m' "$*"; }; yellow(){ printf '\033[33m%s\033[0m' "$*"; }
pass(){ PASS=$((PASS+1)); printf '  %s %s\n' "$(green PASS)" "$1"; }
fail(){ FAIL=$((FAIL+1)); printf '  %s %s\n' "$(red FAIL)" "$1"; [ -n "${2:-}" ] && printf '       %s\n' "$2"; }
skip(){ SKIP=$((SKIP+1)); printf '  %s %s\n' "$(yellow SKIP)" "$1"; }
assert_eq(){ if [ "$2" = "$3" ]; then pass "$1"; else fail "$1" "expected: $2 / actual: $3"; fi; }

# sha256sum shim for macOS (Alpine, where the add-on runs, has it natively)
if ! command -v sha256sum >/dev/null 2>&1 && command -v shasum >/dev/null 2>&1; then
    SHIM="$(mktemp -d)"; printf '#!/bin/sh\nexec shasum -a 256 "$@"\n' > "$SHIM/sha256sum"
    chmod +x "$SHIM/sha256sum"; PATH="$SHIM:$PATH"
fi

TMP_ADDONS="$(mktemp -d)"
if [ "${SKIP_NETWORK_TESTS:-0}" = "1" ] || ! sh "$SCRIPT" --force \
        --addons-dir "$TMP_ADDONS" --ma-id addon_test --python-version python3.14 >/dev/null 2>&1; then
    if [ "${REQUIRE_WATCHER_TESTS:-0}" = "1" ]; then
        fail "required watcher tests could not generate add-on"
        exit 1
    fi
    skip "could not generate add-on (offline or skipped) -- auto-update tests skipped"
    printf '\n== Summary ==\n  passed: %s\n  failed: %s\n  skipped: %s\n' "$PASS" "$FAIL" "$SKIP"
    exit 0
fi
ADDON="$TMP_ADDONS/ma_provider_watcher"
LIB="$ADDON/watcher_lib.sh"; RUNSH="$ADDON/run.sh"

# --- syntax ---
bash -n "$RUNSH" 2>/dev/null && pass "run.sh parses" || fail "run.sh parses"
bash -n "$LIB" 2>/dev/null && pass "watcher_lib.sh parses" || fail "watcher_lib.sh parses"
if command -v shellcheck >/dev/null 2>&1; then
    # Lint both generated files, excluding SC2034 only: run.sh sets
    # CACHE/BUNDLED/HASHFILE/TARBALL_URL that are used by the sourced lib, and the
    # lib sets AUTO_UPDATE/UPDATE_INTERVAL used by run.sh, so each looks "unused"
    # when the files are analysed separately. Every other check still applies.
    # (-x source-following behaves differently across shellcheck versions -- e.g.
    # CI's 0.9.0 -- so exclude the one check that can't work per-file instead.)
    sc_out="$(shellcheck -S warning -e SC2034 "$RUNSH" "$LIB" 2>&1)" \
        && pass "shellcheck clean (generated run.sh + lib)" \
        || fail "shellcheck reported issues" "$sc_out"
else
    skip "shellcheck not installed"
fi

# --- read_options (the blocker + clamp) ---
# read_options parses /data/options.json with jq (installed in the add-on image).
# On a runner without jq the parse degrades every input to the defaults, so skip
# these assertions rather than emit misleading failures (mirrors the sha256sum
# shim above; the alpine CI job installs jq so it exercises them for real).
if command -v jq >/dev/null 2>&1; then
    opt(){ printf '%s' "$1" > "$TMP_ADDONS/o.json"; ( . "$LIB"; read_options "$TMP_ADDONS/o.json"; printf '%s %s' "$AUTO_UPDATE" "$UPDATE_INTERVAL_HOURS" ); }
    assert_eq "auto_update:false yields AUTO_UPDATE=false (the blocker)" "false 24" "$(opt '{"auto_update":false}')"
    assert_eq "auto_update:true yields true"                              "true 24"  "$(opt '{"auto_update":true}')"
    assert_eq "missing auto_update yields false (opt-in default)"         "false 24" "$(opt '{}')"
    assert_eq "interval 0 clamps to 1"        "true 1"   "$(opt '{"auto_update":true,"update_interval_hours":0}')"
    assert_eq "interval negative clamps to 1" "true 1"   "$(opt '{"auto_update":true,"update_interval_hours":-5}')"
    assert_eq "interval non-numeric -> 24"    "true 24"  "$(opt '{"auto_update":true,"update_interval_hours":"x"}')"
    assert_eq "interval null -> 24"           "true 24"  "$(opt '{"auto_update":true,"update_interval_hours":null}')"
    assert_eq "interval 168 kept"             "true 168" "$(opt '{"auto_update":true,"update_interval_hours":168}')"
else
    skip "jq not installed -- read_options assertions skipped"
fi

# --- provider_src precedence + fetch_latest change detection ---
W="$(mktemp -d)"
result="$(
    . "$LIB"
    AUTO_UPDATE=true
    CACHE="$W/cache"; BUNDLED="$W/bundled"; HASHFILE="$W/hash"
    mkdir -p "$BUNDLED"; echo bundled > "$BUNDLED/x"
    src1="$(provider_src)"                                   # no cache -> bundled
    mkdir -p "$W/ytmusic_free"; echo v1 > "$W/ytmusic_free/__init__.py"
    ( cd "$W" && tar -czf pkg.tgz ytmusic_free )
    TARBALL_URL="file://$W/pkg.tgz"
    fetch_latest >/dev/null 2>&1; r1=$?                      # new -> 0
    src2="$(provider_src)"                                   # auto-update on + cache -> cache
    # Opting OUT must revert to the bundled copy even with a cache present.
    AUTO_UPDATE=false; src_off="$(provider_src)"; AUTO_UPDATE=true
    fetch_latest >/dev/null 2>&1; r2=$?                      # unchanged -> 2
    echo v2 > "$W/ytmusic_free/__init__.py"; ( cd "$W" && tar -czf pkg.tgz ytmusic_free )
    fetch_latest >/dev/null 2>&1; r3=$?                      # changed -> 0
    [ "$src1" = "$BUNDLED" ] && [ "$src2" = "$CACHE" ] && [ "$src_off" = "$BUNDLED" ] && echo "$r1 $r2 $r3"
)"
assert_eq "provider_src bundled->cache, off->bundled, fetch_latest new/unchanged/changed = 0/2/0" "0 2 0" "$result"

printf '\n== Summary ==\n  passed: %s\n  failed: %s\n  skipped: %s\n' "$PASS" "$FAIL" "$SKIP"
[ "$FAIL" -gt 0 ] && exit 1 || exit 0
